MvcKutuphane/Controllers/YazarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Entity;

namespace MvcKutuphane.Controllers
{
    public class YazarController : Controller
    {
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        // GET: Yazar
        public ActionResult Index()
        {

            
            var degerler = db.TBLYAZAR.ToList();

            return View(degerler);
        }


        [HttpGet]
        public ActionResult YazarEkle()
        {
            return View();
        }


        [HttpPost]
        public ActionResult YazarEkle(TBLYAZAR p)
        {
            if(!ModelState.IsValid)
            {

                return View("YazarEkle");
            }

            db.TBLYAZAR.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult YazarSil(int id)
        {
            var yazar= db.TBLYAZAR.Find(id);
            db.TBLYAZAR.Remove(yazar);

            db.SaveChanges();

            return RedirectToAction("Index");


        }


        public ActionResult YazarGetir(int id)
        {
            var yzr = db.TBLYAZAR.Find(id);
            return View("YazarGetir",yzr); // YazarGetir actionResult altındaki yzr e ait bilgileri getir.
        }


        public ActionResult YazarGüncelle(TBLYAZAR p)
        {
            var yzr=db.TBLYAZAR.Find(p.ID);
            yzr.AD = p.AD;
            yzr.SOYAD = p.SOYAD;
            yzr.DETAY = p.DETAY;
            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }

}

MvcKutuphane/Views/Yazar/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLYAZAR>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Yazarlar</h2>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Yazar ID</th>
            <th>Yazar Adı</th>
            <th>Yazar Soyadı</th>
            <th>Detay</th>
            <th>SİL</th>
            <th>GÜNCELLE</th>

        </tr>
    </thead>

    <tbody>
        @foreach (var y in Model)
        {
        <tr>
            <td>@y.ID</td>
            <td>@y.AD</td>
            <td>@y.SOYAD</td>
            <td>@y.DETAY</td>
            <th>@Html.ActionLink("Sil","YazarSil", new { id = y.ID }, new {@class="btn btn-danger", onclick="return confirm('Silmek istiyor musunuz?')"})</th>
            <th><a href="/Yazar/YazarGetir/@y.ID" class="btn btn-warning"> <i class="glyphicon glyphicon-refresh"></i> &nbsp;GÜNCELLE</a></th>

        </tr>
        }
    </tbody>
</table>

<a href="/Yazar/YazarEkle/" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> Yeni Yazar Ekle</a>

MvcKutuphane/Views/Yazar/YazarEkle.cshtml
@model MvcKutuphane.Models.Entity.TBLYAZAR

@{
    ViewBag.Title = "YazarEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}


<form method="post">
    <div class="container"  style="margin-top:5px;" >

        <h2>Yeni Yazar Ekle</h2>
        <div class="form-row">
            <div class="form-group col-md-6">

                <label>Yazar Adı:</label>
                @Html.TextBoxFor(y => y.AD, new { @class = "form-control" })
                @Html.ValidationMessageFor(y => y.AD)


            </div>
            <div class="form-group col-md-6">

                <label>Yazar Soyadı:</label>
                @Html.TextBoxFor(y => y.SOYAD, new { @class = "form-control" })
                @Html.ValidationMessageFor(y=> y.SOYAD)

            </div>
        </div>
            <div class="form-group">

            <label>Yazar Detay Bilgileri</label>
            @Html.TextAreaFor(y => y.DETAY, new { @class = "form-control" })

            </div>


            <button class="btn btn-success">EKLE</button>
    </div>
</form>

MvcKutuphane/Views/Yazar/YazarGetir.cshtml
@model MvcKutuphane.Models.Entity.TBLYAZAR


@{
    ViewBag.Title = "YazarGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}



@using (Html.BeginForm("YazarGüncelle","Yazar", FormMethod.Post))
            {

<div class="form-group">

    <label>Yazar ID: </label>
    @Html.TextBoxFor(y=>y.ID, new { @class= "form-control"})

</div>

<div class="form-group">

    <label>Yazar Ad: </label>
    @Html.TextBoxFor(y => y.AD, new { @class = "form-control" })

</div>

<div class="form-group">

    <label>Yazar Soyad: </label>
    @Html.TextBoxFor(y => y.SOYAD, new { @class = "form-control" })

</div>

<div class="form-group">

    <label>Yazar Detay Bilgileri: </label>
    @Html.TextAreaFor(y => y.DETAY, new { @class = "form-control" })

</div>

 <button class="btn btn-warning">Güncelle</button>





            }