MvcKutuphane/Controllers/KitapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Entity;

namespace MvcKutuphane.Controllers
{
    public class KitapController : Controller
    {
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();

        // GET: Kitap
        public ActionResult Index(string p)
        {
            var kitaplar = from k in db.TBLKITAP select k;

            if (!string.IsNullOrEmpty(p))
            {
                kitaplar.Where(m => m.AD.Contains(p));
            }

            //var kitaplar = db.TBLKITAP.ToList();
            return View(kitaplar.ToList());
        }

        [HttpGet]
        public ActionResult KitapEkle()
        {
            List<SelectListItem> deger1 = (from i in db.TBLKATEGORI.ToList()

                                           select new SelectListItem
                                           {
                                               Text = i.AD,
                                               Value = i.ID.ToString()
                                           }).ToList();

            ViewBag.dgr1 = deger1;


            List<SelectListItem> deger2 = (from i in db.TBLYAZAR.ToList()

                                           select new SelectListItem
                                           {
                                               Text = i.AD + " " + i.SOYAD,
                                               Value = i.ID.ToString()
                                           }).ToList();


            ViewBag.dgr2 = deger2;

            return View();
        }

        [HttpPost]
        public ActionResult KitapEkle(TBLKITAP p)
        {
            var ktg = db.TBLKATEGORI.Where(k => k.ID == p.TBLKATEGORI.ID).FirstOrDefault();
            var yzr = db.TBLYAZAR.Where(y => y.ID == p.TBLYAZAR.ID).FirstOrDefault();

            p.TBLKATEGORI = ktg;
            p.TBLYAZAR = yzr;

            db.TBLKITAP.Add(p);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult KitapSil(int id)
        {
            var kitap = db.TBLKITAP.Find(id);
            db.TBLKITAP.Remove(kitap);
            db.SaveChanges();

            return RedirectToAction("Index");
        }


        public ActionResult KitapGetir(int id)
        {
            var ktp = db.TBLKITAP.Find(id);

            List<SelectListItem> deger1 = (from i in db.TBLKATEGORI.ToList()

                                           select new SelectListItem
                                           {
                                               Text = i.AD,
                                               Value = i.ID.ToString()
                                           }).ToList();

            ViewBag.dgr1 = deger1;


            List<SelectListItem> deger2 = (from i in db.TBLYAZAR.ToList()

                                           select new SelectListItem
                                           {
                                               Text = i.AD + " " + i.SOYAD,
                                               Value = i.ID.ToString()
                                           }).ToList();


            ViewBag.dgr2 = deger2;

            return View("KitapGetir",ktp);
        }

        public ActionResult KitapGüncelle(TBLKITAP p)
        {
            var kitap = db.TBLKITAP.Find(p.ID);
            kitap.AD = p.AD;
            kitap.BASIMYIL = p.BASIMYIL;
            kitap.YAYINEVI = p.YAYINEVI;
            kitap.SAYFA = p.SAYFA;
            kitap.DURUM = true;


            var ktg = db.TBLKATEGORI.Where(k => k.ID == p.TBLKATEGORI.ID).FirstOrDefault();
            var yzr = db.TBLYAZAR.Where(y => y.ID == p.TBLYAZAR.ID).FirstOrDefault();

            kitap.KATEGORI = ktg.ID;
            kitap.YAZAR = yzr.ID;

            db.SaveChanges();

            return RedirectToAction("Index");
        }


    }
}

MvcKutuphane/Views/Kitap/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLKITAP>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}


<h2>Kitap İşlemleri</h2>

@using (Html.BeginForm("Index", "Kitap", FormMethod.Get))
            {

    <div style="margin-bottom:15px; margin-top:15px;" >

        <b>Aranacak Kitap Adını Girin: &nbsp;</b> @Html.TextBox("p")
        <input type="submit"  value="Ara" />

    </div>


            }

<table class="table table-bordered" style="margin-top:2em;">

    <thead>
        <tr>
            <th>ID</th>
            <th>Kitap Adı</th>
            <th>Yazar</th>
            <th>Kategori</th>
            <th>Basım Yılı</th>
            <th>Yayınevi</th>
            <th>Sayfa</th>
            <th>Durum</th>
            <th>SİL</th>
            <th>GÜNCELLE</th>

        </tr>
    </thead>

    <tbody>

        @foreach (var k in Model)
        {
            <tr>

                <td>@k.ID</td>
                <td>@k.AD</td>
                <td>@k.TBLYAZAR.AD&nbsp;@k.TBLYAZAR.SOYAD</td>
                <td>@k.TBLKATEGORI.AD</td>
                <td>@k.BASIMYIL</td>
                <td>@k.YAYINEVI</td>
                <td>@k.SAYFA</td>
                <td>@k.DURUM</td>
                <th><a href="/Kitap/KitapSil/@k.ID" class="btn btn-danger"> <i class="glyphicon glyphicon-remove"></i> &nbsp;SİL</a></th>
                <th><a href="/Kitap/KitapGetir/@k.ID" class="btn btn-warning"> <i class="glyphicon glyphicon-refresh"></i> &nbsp;GÜNCELLE</a></th>
            </tr>

        }


    </tbody>

</table>

<a href="/Kitap/KitapEkle/" class="btn btn-success">Yeni Kitap Ekle</a>

MvcKutuphane/Views/Kitap/KitapEkle.cshtml
 @model MvcKutuphane.Models.Entity.TBLKITAP
@{
    ViewBag.Title = "KitapEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form method="post">
    <div class="container" style="margin-top:5px;">

       
        <div class="form-row">

            <h2>Yeni Kitap Ekle</h2>

            <div class="form-group col-md-6">

                <label>Kitap Adı:</label>
                @Html.TextBoxFor(k => k.AD, new { @class = "form-control" })


            </div>
            <div class="form-group col-md-6">

                <label>Kitap Kategori :</label>
                @Html.DropDownListFor(k=> k.TBLKATEGORI.ID, (List<SelectListItem>)ViewBag.dgr1, new {@class= "form-control"})

            </div>

            <div class="form-group col-md-6">

                <label>Kitap Yazarı :</label>
                @Html.DropDownListFor(k=>k.TBLYAZAR.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class="form-control"})

            </div>
            <div class="form-group col-md-6">

                <label>Basım Yılı :</label>
                @Html.TextBoxFor(k => k.BASIMYIL, new { @class = "form-control" })

            </div>
            <div class="form-group col-md-6">

                <label>Sayfa Sayısı :</label>
                @Html.TextBoxFor(k => k.SAYFA, new { @class = "form-control" })

            </div>

            <div class="form-group col-md-6">

                <label>Yayınevi:</label>
                @Html.TextBoxFor(k => k.YAYINEVI, new { @class = "form-control" })

            </div>


        </div>

        <button class="btn btn-success"> KİTAP EKLE</button>
    </div>

    <input type="hidden"  name="Durum" value="True"/>
</form>

MvcKutuphane/Views/Kitap/KitapGetir.cshtml
@model MvcKutuphane.Models.Entity.TBLKITAP
@{
    ViewBag.Title = "KitapGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}


@using (Html.BeginForm("KitapGüncelle", "Kitap", FormMethod.Post))
{

    <div class="form-group">

        <label>Kitap ID: </label>
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })

    </div>

    <div class="form-group">

        <label>Kitap Adı: </label>
        @Html.TextBoxFor(k => k.AD, new { @class = "form-control" })

    </div>
    <div class="form-group">

        <label>Yazar: </label>
        @Html.DropDownListFor(k => k.TBLYAZAR.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })

    </div>

    <div class="form-group">

        <label>Kategori </label>
        @Html.DropDownListFor(k => k.TBLKATEGORI.ID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })

    </div>

    <div class="form-group">

        <label>Basımyılı </label>
        @Html.TextBoxFor(k => k.BASIMYIL, new { @class = "form-control" })

    </div>

    <div class="form-group">

        <label>Yayınevi </label>
        @Html.TextBoxFor(k => k.YAYINEVI, new { @class = "form-control" })

    </div>

    <div class="form-group">

        <label>Sayfa Sayısı </label>
        @Html.TextBoxFor(k => k.SAYFA, new { @class = "form-control" })

    </div>

    <button class="btn btn-warning">Güncelle</button>
    <input type="hidden"  name="Durum" value="True"/>


}