MvcKutuphane/Controllers/PersonelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Entity;

namespace MvcKutuphane.Controllers
{
    public class PersonelController : Controller
    {
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        // GET: Personel
        public ActionResult Index()
        {
            var list= db.TBLPERSONEL.ToList();
            return View(list);
        }

        [HttpGet]
        public ActionResult PersonelEkle()
        {
            return View();

        }

        [HttpPost]
        public ActionResult PersonelEkle(TBLPERSONEL p)
        {
            if(!ModelState.IsValid) // Eğer dataAnnotation kıstasını sağlaıyor ise personel ekle ye yönlendir.
            {
                return View("PersonelEkle");
            }

            db.TBLPERSONEL.Add(p);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult PersonelGetir(int id)
        {
            var prs = db.TBLPERSONEL.Find(id);
            return View("PersonelGetir", prs);
        }

        public ActionResult PersonelGuncelle(TBLPERSONEL p)
        {
            var prs = db.TBLPERSONEL.Find(p.ID);
            prs.PERSONEL = p.PERSONEL;
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult PersonelSil(int id)
        {
            var item = db.TBLPERSONEL.Find(id);
            db.TBLPERSONEL.Remove(item);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

MvcKutuphane/Views/Personel/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLPERSONEL>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Personel İşlemleri</h2>


<table class="table table-bordered">
    <thead>
        <tr>
            <th>Personel ID</th>
            <th>Personel Adı</th>
            <th style="width:fit-content;">SİL</th>
            <th style="width:fit-content;">GÜNCELLE</th>

        </tr>

     
      

    </thead>

    <tbody>
      
            @foreach (var p in Model)
            {
        <tr>
            <td>@p.ID</td>
            <td>@p.PERSONEL</td>
            <td><a href="/Personel/PersonelSil/@p.ID" class="btn btn-danger">Sil</a></td>
            <td> <a href="/Personel/PersonelGetir/@p.ID" class="btn btn-warning">Güncelle</a></td>
        </tr>

            }

        </tbody>

</table>
<a href="/Personel/PersonelEkle/" class="btn btn-success">Personel Ekle</a>

MvcKutuphane/Views/Personel/PersonelEkle.cshtml
@model MvcKutuphane.Models.Entity.TBLPERSONEL
@{
    ViewBag.Title = "PersonelEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Personel Ekle</h2>

<form class="form-group" method="post">

    <div style="margin-top:10px;">
        <label>Personel Adı:</label>
        @*<input style="width:25%;" type="text" class="form-control" name="PERSONEL" placeholder="Kategori adı giriniz..." />*@

        @Html.TextBoxFor(x=>x.PERSONEL, new {@class="form-control"})
        @Html.ValidationMessageFor(x=>x.PERSONEL, "", new { @style="color:red;"} )
    </div>


    <div style="margin-top:10px;">
        <button class="btn btn-info" >Personel Ekle</button>
    </div>

</form>

MvcKutuphane/Views/Personel/PersonelGetir.cshtml
@model MvcKutuphane.Models.Entity.TBLPERSONEL
@{
    ViewBag.Title = "PersonelGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Personel Getir</h2>


@using (Html.BeginForm("PersonelGuncelle", "Personel", FormMethod.Post))
{

<div style="margin-top:15px"></div>

                <div class="form-group">
                    @Html.LabelFor(k => k.ID)
                    @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
                    <br />
                    <label>PERSONEL ADI</label>
                    @Html.TextBoxFor(k => k.PERSONEL, new { @class = "form-control" })
                </div>

                                <div>
                                    <button class="btn btn-warning">Güncelle</button>
                                </div>}