MvcKutuphane/Controllers/UyeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Entity;
using PagedList;
using PagedList.Mvc;

namespace MvcKutuphane.Controllers
{
    public class UyeController : Controller
    {
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        // GET: Uye
        public ActionResult Index(int sayfa=1 )
        {
            var degerler = db.TBLUYELER.ToList().ToPagedList(sayfa, 3);

            //var degerler = db.TBLUYELER.ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult UyeEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UyeEkle(TBLUYELER uye)
        {
            db.TBLUYELER.Add(uye);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult UyeSil(int id)
        {
            var item = db.TBLUYELER.Find(id);
            db.TBLUYELER.Remove(item);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult UyeGetir(int id)
        {
            var item = db.TBLUYELER.Find(id);
            return View("UyeGetir", item);
        }

        public ActionResult UyeGuncelle(TBLUYELER uye)
        {
           var item= db.TBLUYELER.Find(uye.ID);

            item.AD = uye.AD;
            item.SOYAD = uye.SOYAD;
            item.MAIL = uye.MAIL;
            item.KULLANICIADI = uye.KULLANICIADI;
            item.SIFRE = uye.SIFRE;
            item.FOTOGRAF = uye.FOTOGRAF;
            item.TELEFON = uye.TELEFON;
            item.OKUL = uye.OKUL;

            db.SaveChanges();
            return RedirectToAction("Index");
        }




    }
}

MvcKutuphane/Views/Uye/Index.cshtml
@using MvcKutuphane.Models.Entity;
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<TBLUYELER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Üyeler</h2>

<table class="table table-bordered" style="margin-top:2em;">

    <thead>
        <tr>
            <th>ID</th>
            <th>Üye Adı</th>
            <th>Üye Soyad</th>
            <th>Mail</th>
            <th>Kullanıcı Adı</th>
            <th>Sifre</th>
            <th>Fotoğraf</th>
            <th>Telefon</th>
            <th>Okul</th>
            <th>SİL</th>
            <th>GÜNCELLE</th>

        </tr>
    </thead>

    <tbody>

        @foreach (var uye in Model)
        {
        <tr>

            <td>@uye.ID</td>
            <td>@uye.AD</td>
            <td>@uye.SOYAD</td>
            <td>@uye.MAIL</td>
            <td>@uye.KULLANICIADI</td>
            <td>@uye.SIFRE</td>
            <td>@uye.FOTOGRAF</td>
            <td>@uye.TELEFON</td>
            <td>@uye.OKUL</td>
            <th><a href="/Uye/UyeSil/@uye.ID" class="btn btn-danger"> <i class="glyphicon glyphicon-remove"></i> &nbsp;SİL</a></th>
            <th><a href="/Uye/UyeGetir/@uye.ID" class="btn btn-warning"> <i class="glyphicon glyphicon-refresh"></i> &nbsp;GÜNCELLE</a></th>
        </tr>}


    </tbody>
    S
</table>

@Html.PagedListPager((IPagedList)Model, sayfa=>Url.Action("Index", new {sayfa}))

<a href="/Uye/UyeEkle/" class="btn btn-success">Yeni Üye Ekle</a>

MvcKutuphane/Views/Uye/UyeEkle.cshtml
@model MvcKutuphane.Models.Entity.TBLUYELER
@{
    ViewBag.Title = "UyeEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Uye Ekle</h2>


<form method="post">
    <div style="margin-top:5px;">


        <div class="form-row">



            <div class="form-group col-md-6">

                <label>Üye Adı:</label>
                @Html.TextBoxFor(k => k.AD, new { @class = "form-control" })


            </div>
            <div class="form-group col-md-6">

                <label>Üye Soyadı :</label>
                @Html.TextBoxFor(k => k.SOYAD, new { @class = "form-control" })

            </div>

            <div class="form-group col-md-6">

                <label>Üye Maili:</label>
                @Html.TextBoxFor(k => k.MAIL, new { @class = "form-control" })

            </div>
            <div class="form-group col-md-6">

                <label>Kullanıcı Adı :</label>
                @Html.TextBoxFor(k => k.KULLANICIADI, new { @class = "form-control" })

            </div>
            <div class="form-group col-md-6">

                <label>Sifre :</label>
                @Html.TextBoxFor(k => k.SIFRE, new { @class = "form-control" })

            </div>

            <div class="form-group col-md-6">

                <label>Fotoğraf:</label>
                @Html.TextBoxFor(k => k.FOTOGRAF, new { @class = "form-control" })

            </div>

            <div class="form-group col-md-6">

                <label>Telefon:</label>
                @Html.TextBoxFor(k => k.TELEFON, new { @class = "form-control" })

            </div>

            <div class="form-group col-md-6">

                <label>Okul:</label>
                @Html.TextBoxFor(k => k.OKUL, new { @class = "form-control" })

            </div>

        </div>

        <button class="btn btn-success"> ÜYE EKLE</button>
    </div>
</form>

MvcKutuphane/Views/Uye/UyeGetir.cshtml
@model MvcKutuphane.Models.Entity.TBLUYELER
@{
    ViewBag.Title = "UyeGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Üye Güncelleme İşlemleri</h2>

@using (Html.BeginForm("UyeGuncelle", "Uye", FormMethod.Post))
{

    <div class="form-group">

        <label>Uye ID: </label>
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })

    </div>

    <div class="form-group">

        <label>Üye Adı: </label>
        @Html.TextBoxFor(k => k.AD, new { @class = "form-control" })

    </div>
    <div class="form-group">

        <label>Üye Soyad: </label>
        @Html.TextBoxFor(k => k.SOYAD, new { @class = "form-control" })

    </div>

    <div class="form-group">

        <label>Mail </label>
        @Html.TextBoxFor(k => k.MAIL, new { @class = "form-control" })

    </div>

    <div class="form-group">

        <label>Kullanıcı Adı </label>
        @Html.TextBoxFor(k => k.KULLANICIADI, new { @class = "form-control" })

    </div>

    <div class="form-group">

        <label>Sifre </label>
        @Html.TextBoxFor(k => k.SIFRE, new { @class = "form-control" })

    </div>

    <div class="form-group">

        <label>Fotoğraf </label>
        @Html.TextBoxFor(k => k.FOTOGRAF, new { @class = "form-control" })

    </div>
    <div class="form-group">

        <label>Telefon </label>
        @Html.TextBoxFor(k => k.TELEFON, new { @class = "form-control" })

    </div>
    <div class="form-group">

        <label>Okul </label>
        @Html.TextBoxFor(k => k.OKUL, new { @class = "form-control" })

    </div>

    <button class="btn btn-warning">Güncelle</button>
}